"""renew tables

Revision ID: b94f1af04a47
Revises: 477628539e2a
Create Date: 2023-06-20 15:19:25.939604

"""
from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b94f1af04a47"
down_revision = "477628539e2a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
